### ISSUE TITLE
Почему автоматическое приведение не используется для не-булевых?

### ISSUE THREAD

**Issue by sanmai** [roistat/php-code-conventions#13]
Не объяснено, почему автоматическое приведение *никогда* не используется для не-булевых.

Например, есть рекомендация:

```php
if ((int)$request->postData('sum') === 100) {
```

И есть рекомендация использовать максимально возможную типизацию:

```php
function postData(string $name): int {
```
Для функции с такой сигнатурой как выше требование строгое сравнения не-булевых с приведением типа не имеет никакого смысла. Обычное сравнение даст столь же надёжный результат.

**Comment by flrnull** [comment]
Смысл в том, что postData выдает значение по ключу, но там не всегда int. 
Например, в `postData('name')` выдаст `string`. 

Да, можно создать отдельный типизированный объект Request с нужными полями для каждого экшена в каждом контроллере, но в данном правиле речь не про организацию MVC, а про условия.)

**Comment by sanmai** [comment]
Значит ли что вы оправдываете нежелание писать хороший и правильный код банальной ленью?

**Comment by flrnull** [comment]
Я не очень понял, как мы так быстро перепрыгнули с обсуждения конкретного правила к нежеланию писать хороший код.

Я ответил на замечание. `function postData(string $name): int {` — такой код ошибочный. Но если есть предложения, как доработать и улучшить правило, мы только за.
