### ISSUE TITLE
Почему комментарии запрещены?

### ISSUE THREAD

**Issue by sanmai** [roistat/php-code-conventions#14]
Не объяснено, почему комментарии запрещены, и почему они - однозначно признак плохого кода.

Я понимаю откуда от этой идеи идут корни: правила разрабатывались для проектов, которые не были в разработке десять и больше лет. На проекте, который только был запущен в работу, все всё знают и все всё помнят. На проекте, который был сдан в эксплуатацию много лет назад никто не будет вчитываться в код, когда срочно нужно исправить какую-то редкую проблему. Комментарии как раз нужны чтобы код *не читать* в таких ситуациях.

Если посмотреть на другие проекты со сроком жизни в десятилетия, то они просто изобилуют комментариями. Взять хотя бы ядро Linux. Потому требование отсутствия комментариев удивляет.

Может быть наоборот требуется чтобы в вашем коде никто посторонний не мог разобраться? Тогда это логичное требование, только добавить к нему такое объяснение.

**Comment by bfday** [comment]
Есть понятие как "самодокументированный код". Наверное, это и имелось ввиду. И да, для очень больших проектов подход недостаточно хорош, также как и подход "много букав и частных случаев в комментах". Этот случай лучше разобрать детальнее.

**Comment by flrnull** [comment]
Не нужно смешивать в одну кучу комментарии в коде и документацию. Никто не запрещает (а даже наоборот) сделать файл README в корне своего компонента и описать какие-то цели компонента, какие задачи он решает, принципиальные моменты его реализации, продуктовые требования и возможные неочевидные решения. 

При этом поведение компонента в разных кейсах лучше описывать тестами. Но, опять же, если тесты будут стоить очень дорого и большого профита не дадут, то можно и это тоже описать в README. 

Но сам код, каждый метод и каждый if объяснять не надо. Если приходится это объяснять, значит код не удовлетворяет основным требованиям. 

> Если посмотреть на другие проекты со сроком жизни в десятилетия, то они просто изобилуют комментариями. Взять хотя бы ядро Linux.

Открыл ядро линукса, беру случайный файл `kernel/async.c`. Что я в нём вижу:

Вначале файла есть то, о чем я писал выше — цель компонента, основные положения. В общем, то же самое README.

Дальше я вижу первую часть кода, которая не особо читабельна и никак не сопровождается комментариями. А после неё часть всё так же слабо читаема, но там каждый блок сопровождается комментарием, например:

```
	/* 2) remove self from the pending queues */
	spin_lock_irqsave(&async_lock, flags);
	list_del_init(&entry->domain_list);
	list_del_init(&entry->global_list);

	/* 3) free the entry */
	kfree(entry);
	atomic_dec(&entry_count);

	spin_unlock_irqrestore(&async_lock, flags);

	/* 4) wake up any waiters */
	wake_up(&async_done);
```

Вместо _Extract Method_ разработчик здесь решил оставить комментарий и отделить блок пустыми строками. И так мы видим огромный метод, разбитый пустыми строками на смысловые блоки, где каждый блок сопровождается комментарием. Возможно это особенности подхода, а возможно просто разработчику было некогда писать качественный код (проект огромный, писанины много). Язык компилируемый, то есть метод вместо комментария не должен был добавить накладные расходы. И в этом файле почти все комментарии кода именно такие. В наших проектах такой код считается злокачественным и ревью не пройдёт. 

Я ни в коем случае не критикую ядро линукса, просто у нас проекты не такие крупные (у нас десятки, а там тысячи разработчиков), и мы можем себе позволить контролировать качество кода. В ядре линукса это просто было бы слишком дорого.

Возможно надо в правиле упомянуть, что README не запрещено, а наоборот требуется.

**Comment by sanmai** [comment]
Не очень понятно откуда у вас есть убеждение что выделять код в фукнцию, которая будет использоваться один раз, лучше, чем тот же фрагмент откомментировать. Есть какие-то факты или доказательства что это лучше? В каком университете учат, простите, такому?

**Comment by ilyaguy** [comment]
Кстати, а что плохого в отделении смысловых блоков пустыми строками?

**Comment by flrnull** [comment]
> Кстати, а что плохого в отделении смысловых блоков пустыми строками?

Ничего. Просто отделять надо те вещи, которые нельзя вынести в отдельный понятный метод. В примере выше видно, что это классический кейс, для которого создан Extract Method.
