### ISSUE TITLE
Ассоциативный массив мы используем как hashmap

### ISSUE THREAD

**Issue by lex111** [roistat/php-code-conventions#17]
Мне кажется этот раздел нужно дополнить, непонятно, как надо, почему такое вообще правило.

> Нельзя сортировать ассоциативные массивы

Тогда нужно, наверное, добавить, что ассоциативный массив используется как неизменяемая хеш-таблица?

**Comment by flrnull** [comment]
А что ты здесь имеешь в виду под «неизменяемой хеш-таблицей»? 

Поясню проблематику. В PHP массивы не совсем стандартны и смешивают возможности массива и hashmap. Когда у разработчика на руках ассоциативный массив, а он его сортирует — это вызывает недоумение и вопросы, что именно разработчик тут ожидал получить и точно ли он ничего не перепутал. Может он забыл, что у него были ключ-значения и подумал, что у него массив/список. 

Аналогично и в обратную сторону. Когда на руках обычный массив, в котором нет строковых ключей, то странно видеть обращения к нему, как к ассоциативному. Это мешает пониманию кода.

**Comment by lex111** [comment]
> А что ты здесь имеешь в виду под «неизменяемой хеш-таблицей»?

Хеш-таблицы ведь не иммутабельные изначально? У меня вопрос был такой, то есть можно сортировать массивы, если в нём только используется строковые ключи, а как это отслеживать?

**Comment by flrnull** [comment]
> У меня вопрос был такой, то есть можно сортировать массивы, если в нём только используется строковые ключи, а как это отслеживать?

Отсортировать можно, просто ключи потеряются и останутся только числовые индексы. 

> Хеш-таблицы ведь не иммутабельные изначально?

У ассоциативного массива можно менять ключи и значения — в этом нет проблемы. Конечно, чем меньше мутаций, тем лучше. По аналогии с объектами. Но прям как жесткое правило возможно нет смысла это записывать. Массивы в отличии от объектов часто используются как локальные переменные, у которых ограниченная область видимости, и их часто нет смысла плодить, проще просто изменить нужное значение.

**Comment by lex111** [comment]
Ок, понятно.
