### ISSUE TITLE
Вместо лишней конкатенации используем подстановку переменных в двойных кавычках

### ISSUE THREAD

**Issue by andrew-svirin** [roistat/php-code-conventions#39]
Почему не рассмтаривается sprintf() функция? Она очень удобная для работы со строками.
```
$string = "Object with type \"{$object->type()}\" has been removed";
```

```
$string = sprintf('Object with type "%s" has been removed', $object->type());
```

**Comment by flrnull** [comment]
Явного запрета на sprintf нет. Если в проекте она уже используется, то можно использовать и ее. Тут речь исключительно про то, как работать с кавычками. Их не надо лишний раз разбивать и конкатенировать.

А так sprintf имеет право на жизнь, да. В рамках общего CodeConv, думаю, ни запрещать, ни обязывать к применению не нужно.
