### ISSUE TITLE
Возможная ошибка

### ISSUE THREAD

**Issue by NelinD** [roistat/php-code-conventions#4]
[Тут](https://github.com/roistat/php-code-conventions#-%D0%9C%D0%B5%D1%82%D0%BE%D0%B4-%D1%81-%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B8%D0%BC-%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE%D0%BC-%D0%BD%D0%B5%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2-%D0%90-%D0%BC%D0%BE%D0%B6%D0%B5%D1%82-%D0%B1%D1%8B%D1%82%D1%8C-%D0%B7%D0%B0%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD-chain-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%BC) похоже некорректный код "до"

**Comment by flrnull** [comment]
Спасибо, исправили.
