### ISSUE TITLE
Рекомендации не следуют общепринятым стандартам (PSR-2...)

### ISSUE THREAD

**Issue by sanmai** [roistat/php-code-conventions#9]
PSR-2 говорит что [фигурные скобки должны быть на следующей строке](https://www.php-fig.org/psr/psr-2/):

```php
public function sampleMethod($a, $b = null)
{

}
```
В примерах фигурная скобка идёт на той же строке.

Пока эти рекомендации не учитывают существующие стандарты и правила, их невозможно принять и использовать без доработки, если вы уже учитываете существующие стандарты. Если   в правилах было написано что код должен соответствовать PSR-2, и если правила дополнить требованием выполнения этих рекомендаций, то возникает конфликт.

Если есть желание чтобы этими правилами могло пользоваться как можно больше человек, правила должны учитывать принятые стандарты.

**Comment by flrnull** [comment]
Расположение скобок относится к Code Style и выходит за рамки данного документа. Мы в целом придерживаемся PSR'ов, но есть исключения. И расположение данной скобки — одно из них. И в целом для нас PSR — это про всё остальное, но не про Code Style. 

Чтобы решить проблему для своего проекта, могу предложить такие work around:
- Можно использовать авточекер для проверки Code Style и тогда никто не сможет ошибиться и проблемы не возникнет
- Можно ссылаясь на этот документ делать пометку, что на Code Style не надо обращать внимание
- Можно скопировать документ к себе, пройтись автозаменой и использовать его с псевдокодом со своим Code Style

**Comment by sanmai** [comment]
Тогда можно ли попросить дополнить этот документ фразой про расположение скобок? Что типа "скобки указаны для примера, документ не требует чтобы..."

**Comment by flrnull** [comment]
Да, вверху можно дописать дисклеймер, что все листинги кода написаны с рандомным Code Style и обращать внимание на него не надо и надо следовать принятому в проекте Code Style.

Допишем.

**Comment by sanmai** [comment]
Переоткройте эту проблему, пожалуйста, пока не дописали.

**Comment by flrnull** [comment]
> Обратите внимание: Code Style в примерах может отличаться от Code Style вашего проекта. Придерживаться надо тому Code Style, который принят у вас. Code Conv не об этом.

Добавил.
